apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  mysql-username: YWRtaW4=          # this is base64 of "admin"
  mysql-password: YWRtaW4xMjM=  # this is base64 of "admin12345"